services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video-downloader-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: DOWNLOAD_FOLDER
        value: /tmp/downloads
    healthCheckPath: /

databases:
  - name: video-downloader-db
    databaseName: video_downloader
    user: video_downloader